from setuptools import setup, find_namespace_packages

setup(name='neurino',
      packages=find_namespace_packages(include=["nnunet_mednext", "nnunet_mednext.*"]),
      version='1.7.0',
      description='NeurINO: 2D-to-3D Knowledge Transfer for Neuron Segmentation',
      url='https://github.com/yy0007/NeurINO',
      license='MIT',
      install_requires=[
            "torch>1.10.0",
            "tqdm",
            "dicom2nifti",
            "scikit-image>=0.14",
            "medpy",
            "scipy",
            "batchgenerators>=0.23",
            "numpy",
            "scikit-learn",
            "SimpleITK",
            "pandas",
            "requests",
            "nibabel", 
            "tifffile", 
            "matplotlib",
      ],
      entry_points={
        'console_scripts': [
            'neurino_convert_decathlon_task = nnunet_mednext.experiment_planning.nnUNet_convert_decathlon_task:main',
            'neurino_plan_and_preprocess = nnunet_mednext.experiment_planning.nnUNet_plan_and_preprocess:main',
            'neurino_train = nnunet_mednext.run.run_training:main',
            'neurino_train_DP = nnunet_mednext.run.run_training_DP:main',
            'neurino_train_DDP = nnunet_mednext.run.run_training_DDP:main',
            'neurino_predict = nnunet_mednext.inference.predict_simple:main',
            'neurino_ensemble = nnunet_mednext.inference.ensemble_predictions:main',
            'neurino_find_best_configuration = nnunet_mednext.evaluation.model_selection.figure_out_what_to_submit:main',
            'neurino_print_available_pretrained_models = nnunet_mednext.inference.pretrained_models.download_pretrained_model:print_available_pretrained_models',
            'neurino_print_pretrained_model_info = nnunet_mednext.inference.pretrained_models.download_pretrained_model:print_pretrained_model_requirements',
            'neurino_download_pretrained_model = nnunet_mednext.inference.pretrained_models.download_pretrained_model:download_by_name',
            'neurino_download_pretrained_model_by_url = nnunet_mednext.inference.pretrained_models.download_pretrained_model:download_by_url',
            'neurino_determine_postprocessing = nnunet_mednext.postprocessing.consolidate_postprocessing_simple:main',
            'neurino_export_model_to_zip = nnunet_mednext.inference.pretrained_models.collect_pretrained_models:export_entry_point',
            'neurino_install_pretrained_model_from_zip = nnunet_mednext.inference.pretrained_models.download_pretrained_model:install_from_zip_entry_point',
            'neurino_change_trainer_class = nnunet_mednext.inference.change_trainer:main',
            'neurino_evaluate_folder = nnunet_mednext.evaluation.evaluator:nnunet_evaluate_folder',
            'neurino_plot_task_pngs = nnunet_mednext.utilities.overlay_plots:entry_point_generate_overlay',
            'neurino_region_based_evaluation = nnunet_mednext.evaluation.region_based_evaluation:main',
        ],
    },
      keywords=['deep learning', 'image segmentation', 'neuron segmentation',
                'neuron reconstruction', 'nnU-Net', 'MedNeXt', 'NeurINO', 'DINOv3']
      )
